web:
  build: ./docker/Dockerfiles/custom-web
  volumes:
    - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
    - ./app/public_html:/var/www/html
    - ./docker/000-default.conf:/etc/apache2/sites-enabled/000-default.conf:ro
  links:
    - mysql:mysql
  environment:
    VIRTUAL_HOST: api.visitwrapper.dev
web2:
  image: droptica/drupal-apache:7-xdebug
  volumes:
    - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
    - ./app/front:/var/www/html
    - ./docker/000-default.conf:/etc/apache2/sites-enabled/000-default.conf:ro
  links:
    - mysql:mysql
  environment:
    VIRTUAL_HOST: visitwrapper.dev
web3:
  image: droptica/drupal-apache:7-xdebug
  volumes:
    - ./app/client:/var/www/html
    - ./docker/000-default.conf:/etc/apache2/sites-enabled/000-default.conf:ro
  links:
    - mysql:mysql
  environment:
    VIRTUAL_HOST: client.visitwrapper.dev
mysql:
  image: mysql:5.7
  volumes:
    - ./docker/database:/var/lib/mysql
    - ./docker/my.conf:/etc/mysql/conf.d/custom.cnf:ro
  environment:
    MYSQL_ROOT_PASSWORD: 123
    MYSQL_DATABASE: db
    MYSQL_USER: user
    MYSQL_PASSWORD: pass

phpmyadmin:
  image: nazarpc/phpmyadmin
  links:
    - mysql:mysql
  environment:
      VIRTUAL_HOST: phpmyadmin.visitwrapper.dev
